# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: Troy Pulli  # Name of your website
tagline: DeFion Labs  # Set your preferred page title
description: Troy Pulli  # Also used as a meta description
favicon: https://raw.githubusercontent.com/TroyPulli/troypulli.github.io/main/1.png # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
logo: https://raw.githubusercontent.com/TroyPulli/troypulli.github.io/main/1.png # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://troypulli.com # URL of your website
locale: en_GB # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
twitter:
  username: defion_labs # Used for SEO
image:
  path: https://raw.githubusercontent.com/TroyPulli/troypulli.github.io/main/1.png # Used for SEO
  type: png # File format of image. Change according to your image. Supported types: https://en.wikipedia.org/wiki/Media_type#Common_examples
  height: 100 # Pixels
  width: 100
  alt: logo

# Verified Badge Configuration
badge: true  # Set to 'true' or 'false' to enable / disable the badge
icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
color: '#dfb221'  # Define the color of the badge
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
